### ISSUE TITLE
Не удаляет за собой временные файлы

### ISSUE THREAD

**Issue by khorevaa** [nixel2007/oscript-fluent#13]
После выполнения текствой команды не удялет за собой временный файл.

**Comment by nixel2007** [comment]
Временные файлы должны убираться при вызова терманального метода конвейера. Например - https://github.com/nixel2007/oscript-fluent/blob/511734a177a7601494178f117f490212b3ffb5b7/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81%D0%BE%D1%80%D0%9A%D0%BE%D0%BB%D0%BB%D0%B5%D0%BA%D1%86%D0%B8%D0%B9.os#L692

Дай код, который не удаляет за собой временные файлы.

**Comment by khorevaa** [comment]
![default](https://user-images.githubusercontent.com/665525/34615338-998375ce-f245-11e7-8352-be87efd477ec.png)
Папка темп !! После работы скрипта

**Comment by khorevaa** [comment]
Внутри файлов
```bsl
﻿Процедура ОбработкаОповещения(Результат, ДополнительныеПараметры) Экспорт

	Элемент = Неопределено;
	Элемент1 = Неопределено;
	Элемент2 = Неопределено;
	
	ДополнительныеПараметры.Свойство("Элемент", Элемент);
	ДополнительныеПараметры.Свойство("Элемент1", Элемент1);
	ДополнительныеПараметры.Свойство("Элемент2", Элемент2);

	Результат = Элемент1.Парсер.Приоритет() > Элемент2.Парсер.Приоритет()

КонецПроцедуры
```

**Comment by nixel2007** [comment]
После работы какого скрипта? :)

**Comment by khorevaa** [comment]
После вызова функции сортировки

```bsl
Функция Сортировать(Знач ФункцияСравнения = Неопределено, Знач ДополнительныеПараметры = Неопределено) Экспорт
	
	Если ФункцияСравнения = Неопределено Тогда
		ФункцияСравнения = ПроцессорыКоллекций.СтандартнаяФункцияСравнения();
	Иначе
		Если ТипЗнч(ФункцияСравнения) = Тип("Строка") Тогда
			ФункцияСравнения = СформироватьВременноеОписаниеОповещения(ФункцияСравнения, ДополнительныеПараметры);
		КонецЕсли;
	КонецЕсли;

	ПоложитьЯчейкуВКонвейер("Сортировать", ФункцияСравнения);
	Возврат ЭтотОбъект;
	
КонецФункции
```

**Comment by nixel2007** [comment]
Сортировка - это не терминальный метод. Дай свой скрипт полностью

**Comment by khorevaa** [comment]
https://github.com/khorevaa/cli/blob/develop/src/core/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/internal/path/%D0%92%D1%8B%D0%B1%D0%BE%D1%80%D0%A1%D0%BE%D0%B2%D0%BF%D0%B0%D0%B4%D0%B5%D0%BD%D0%B8%D0%B9.os#L152

**Comment by khorevaa** [comment]
Т.к. у меня это выше рекурсия то файликов просто море с одним и тем же текстом 
https://github.com/khorevaa/cli/blob/develop/src/core/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/internal/path/%D0%92%D1%8B%D0%B1%D0%BE%D1%80%D0%A1%D0%BE%D0%B2%D0%BF%D0%B0%D0%B4%D0%B5%D0%BD%D0%B8%D0%B9.os#L135

**Comment by khorevaa** [comment]
Кстати может стоит сделать кэш строк и не инициализировать каждый раз

**Comment by nixel2007** [comment]
Подтверждаю, метод ВМассив не вызывает очистку описаний оповещений. А так же ряд терминальных методов, у которых нет входящих параметров-описаний оповещения.

**Comment by khorevaa** [comment]
@nixel2007 Может стоит перейти на "Выполнить()"?

**Comment by nixel2007** [comment]
Тебе не критична зависимость от 16-17 движка? Я думаю выпустить на днях релиз notify+fluent, который вместо создания временных файлов для обработчиков будет создавать объекты напрямую, через ЗагрузитьСценарийИзСтроки

**Comment by nixel2007** [comment]
От выполнить я отказался изначально - небезопасно - протекают глобальные переменные и переменные скоупа метода. Всё должно быть изолированно

**Comment by khorevaa** [comment]
Использую 18 версию так, что выпускай.. )

**Comment by khorevaa** [comment]
На delegate бы еще перейти ) Удачная библиотека

**Comment by nixel2007** [comment]
Я пожалуй выпущу два релиза - баг-фикс этого добра в рамках старого движка, а потом уже на 18ом движке. Дай мне пару дней.

**Comment by khorevaa** [comment]
Да хоть 5  )))

**Comment by nixel2007** [comment]
Может быть, может быть. Надо подумать, как сохранить совместимость. Полного отказа от notify я не хочу по идеологическим причинам.

**Comment by khorevaa** [comment]
Просто если бы был делегат я бы не использовал текст )))
Да и в ряде других случаешь пришлось использовать текст вместо делегата....
Лень много писать

**Comment by nixel2007** [comment]
Погоди, ты же знаешь, что можно писать не текст, а описание оповещения из библиотеки notify?

**Comment by khorevaa** [comment]
Да.. Но там много буков.. надо писать

**Comment by nixel2007** [comment]
Понял. Раз есть потребность, подумаю, что можно сделать.

**Comment by artbear** [comment]
Ага, делегат явно удобнее=проще, чем 1С-кие жуткие Оповещения :(
