### ISSUE TITLE
Интеграционный тест №7

### ISSUE THREAD

**Issue by 240596448** [nixel2007/oscript-fluent#19]
https://github.com/nixel2007/oscript-fluent/blob/1376ed68db24f3f97670c506f8ff2fa0c36ef021/tests/%D0%98%D0%BD%D1%82%D0%B5%D0%B3%D1%80%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B9%D0%A2%D0%B5%D1%81%D1%82.os#L152

Тест не проходит из-за стандартной функции сравнения и заглавной "Я". Так задумано?

**Comment by 240596448** [comment]
Тест №7 внезапно не прошел. С чего бы это? 
Оскипт для виндовс и для линукс выдает разное поведение сортировки? 
В баше "A","B","C" все меньше "а".

**Comment by nixel2007** [comment]
Возможно влияет установленная кодовая страница и порядок символов.
