### ISSUE TITLE
Ошибка при использовании Новый УправлениеКонфигуратором() 

### ISSUE THREAD

**Issue by spawnax** [nixel2007/oscript-fluent#33]
{Модуль C:\Program Files\OneScript\lib\fluent\src\Классы\ПроцессорКоллекций.os / Ошибка в строке: 966 / Внешнее исключение (ScriptEngine.Compiler.CompilerException): {Модуль <string 0B4EDC33> / Ошибка в строке: 11,9 / Неизвестная операция} 
        Первый, Второй -> СтроковыеФункции.СравнитьВерсии(Первый.НомерВерсии,  Второй.НомерВерсии) < 0}

**Comment by nixel2007** [comment]
Кажется, уже обсуждали, был старый флюент.
