### ISSUE TITLE
Ленивое выполнение конвейерных методов в случае "неполных" терминальных методов

### ISSUE THREAD

**Issue by nixel2007** [nixel2007/oscript-fluent#4]
```java
  public Optional<Article> getFirstJavaArticle() {  
    return articles.stream()
        .filter(article -> article.getTags().contains("Java"))
        .findFirst();
    }
```

Pretty cool right? We first use the filter operation to find all articles that have the Java tag, then used the findFirst() operation to get the first occurrence. Since streams are lazy and filter returns a stream, this approach only processes elements until it finds the first match.

**Comment by khorevaa** [comment]
А можно по русски. А то я  допустим перевести не могу

**Comment by nixel2007** [comment]
Из-за того, что стримы - ленивые и используется ПолучитьПервый фильтрация отрабатывает не на каждый элемент массива, а до первого срабатывания фильтра. Оптимизация типа. 

В текущей реализации сначала целиком выполняются все конвейерные методы, а только потом идёт терминальный ПолучитьПервый. 

Это не критично, но подумать над ленивостью стоит. Где-нибудь в 0.3. В 0.2 я готовлю документацию по всем методам (частично сделано), смену сигнатуры ДляКаждого (сделано) , смену имён стандартных обработчиков (сделано), поддержку 1.0.15 (сделано) и поддержку структур и соответствий. 
Завтра запушу, если интересно.

**Comment by khorevaa** [comment]
Спасибо. Теперь понял что хочешь )) Мне интересно.
