### ISSUE TITLE
Читать шаблон один раз

### ISSUE THREAD

**Issue by dmpas** [nixel2007/oscript-fluent#7]
Операцию чтения можно вызывать единожды.
https://github.com/nixel2007/oscript-fluent/blob/master/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81%D0%BE%D1%80%D0%9A%D0%BE%D0%BB%D0%BB%D0%B5%D0%BA%D1%86%D0%B8%D0%B9.os#L467

а вот это https://github.com/nixel2007/oscript-fluent/blob/master/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81%D0%BE%D1%80%D0%9A%D0%BE%D0%BB%D0%BB%D0%B5%D0%BA%D1%86%D0%B8%D0%B9.os#L476 навевает воспоминания об ООП :trollface: 

поди и правда сделать загрузку сценария из строки?...

**Comment by artbear** [comment]
@dmpas Ты что, придет парень с коротким именем, но длинным текстом, и как воспользуется :)

PS а вообще загрузка сценария из строки давно нужна!

**Comment by dmpas** [comment]
> а вообще загрузка сценария из строки давно нужна!

@artbear дык путь давно известен - задачка в движок, призыв, голосование, оброс какашками, профит.

**Comment by nixel2007** [comment]
Первое - согласен.
Второе - я не думаю, что ООП тут сильно поможет. Текст функции я меняю через стрзамену. Конструктор объектов (классов?) из кода я, если честно, я видел только в javascript с их магией через прототипы.

Я нашел такое решение, если есть предложение, как его можно улучшить (в идеале улучшив производительность), я только за :)

Updated: А, я понял причем тут ооп. действительно, тссс...)

**Comment by nixel2007** [comment]
@dmpas можно тебя просить смотреть ветку девелоп? О_о или даже feature/tests. А то в мастере пока без документации и без тестов от слова совсем.

**Comment by dmpas** [comment]
> без документации и без тестов

в топку слова, я код смотрю :)

**Comment by nixel2007** [comment]
@dmpas ну там просто еще чуток наворотов добавилось. 
https://github.com/nixel2007/oscript-fluent/compare/master...feature/tests
